spring.application.name=bookmanager

spring.datasource.url=jdbc:mysql://localhost:3306/bookmanager
spring.datasource.username=root
spring.datasource.password=Kingdom11x4325+

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
